apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persona-creator-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cinder-high-speed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persona-creator-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cinder-high-speed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persona-creator-generated-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cinder-high-speed
