/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './views/**/*.ejs',
    './src/**/*.js',
    './public/**/*.{html,js}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'rgb(var(--primary-rgb) / <alpha-value>)',
        'on-primary': 'rgb(var(--on-primary-rgb) / <alpha-value>)',
        'primary-container': 'rgb(var(--primary-container-rgb) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--on-primary-container-rgb) / <alpha-value>)',
        secondary: 'rgb(var(--secondary-rgb) / <alpha-value>)',
        'on-secondary': 'rgb(var(--on-secondary-rgb) / <alpha-value>)',
        surface: 'rgb(var(--surface-rgb) / <alpha-value>)',
        'on-surface': 'rgb(var(--on-surface-rgb) / <alpha-value>)',
        'surface-variant': 'rgb(var(--surface-variant-rgb) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--on-surface-variant-rgb) / <alpha-value>)',
        background: 'rgb(var(--background-rgb) / <alpha-value>)',
        'on-background': 'rgb(var(--on-background-rgb) / <alpha-value>)',
        outline: 'rgb(var(--outline-rgb) / <alpha-value>)',
        'surface-container': 'rgb(var(--surface-container-rgb) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--surface-container-low-rgb) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest-rgb) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--surface-container-highest-rgb) / <alpha-value>)',
        error: 'rgb(var(--error-rgb) / <alpha-value>)',
        'on-error': 'rgb(var(--on-error-rgb) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '12px',
        'container-max': '1440px',
        base: '8px',
        'stack-md': '24px',
        'margin-mobile': '16px',
        gutter: '24px',
        'margin-desktop': '48px',
        'stack-lg': '48px',
      },
      fontFamily: {
        'headline-xl': ['Outfit'],
        'label-md': ['Inter'],
        'headline-lg': ['Outfit'],
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Outfit'],
        'label-sm': ['Inter'],
        'headline-md': ['Outfit'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'headline-xl': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
    require('tailwindcss-animate'),
  ],
}
